title: 鬰见美好阅读团队|书香越过山峦
page-top-title: 鬰见美好
top-section-bg-text: 书香越过山峦
backgrounds:
  - static/assets/img/屏幕截图 2026-08-20 223717.png
  - static/assets/img/774.png
background-interval-ms: 7000
background-overlay: 0.52
copyright-text:  Encountering beauty team 2026 All Rights Reserved.'
sections:
  - id: home
    nav: HOME
    title: 鬰见美好&ensp;|&ensp;阅读团队
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
